movieproject/movieproject/movieapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movies/<int:id>/',views.detail,name='detail'),
    path('add/',views.addmovies,name='addmovies'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]

movieproject/movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movies(models.Model):
    name=models.CharField(max_length=200)
    year=models.IntegerField()
    desc=models.TextField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieproject/movieapp/forms.py
from django import forms
from .models import movies
class FormMovie(forms.ModelForm):
    class Meta:
        model = movies
        fields = ['name','year','desc','img']

movieproject/movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import FormMovie
from .models import movies


# Create your views here.
def index(request):
    obj=movies.objects.all()
    return render(request,"movie.html",{'result':obj})
def detail(request, id):
    movie = movies.objects.get(id=id)
    return render(request,"details.html",{'movies':movie})
def addmovies(request):
    if request.method=="POST":
        name = request.POST.get('name')
        year = request.POST.get('year')
        desc = request.POST.get('desc')
        img = request.FILES['img']
        user=movies(name=name,year=year,desc=desc,img=img)
        user.save()
    return render(request,"add.html")
def update(request,id):
    movie = movies.objects.get(id=id)
    form = FormMovie(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method == "POST":
        movie=movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

movieproject/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter the movie name"><br>
  <input type="text" name="year" placeholder="Enter the movie year"><br>
  <input type="text" name="desc" placeholder="Enter the movie description"><br>
  <input type="file" name="img"><br>
  <input type="submit">
</form>
{% endblock %}

movieproject/movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movies</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-black bg-dark">
  <a class="navbar-brand" href="/">
      Movie Lists
  </a>
</nav>
<nav class="navbar navbar-black bg-dark">
  <a class="navbar-brand" href="add">
       <a class="btn btn-warning" href="{% url 'movieapp:addmovies'%}">Add</a>
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/movieproject/templates/delete.html
<form method="post">
    {% csrf_token %}
    Are you sure want to delete?<br>
    <input type="submit">
</form>

movieproject/movieproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movies.img.url}}" width="500" height="500"><br>
        </div>

<div class="col-md-6">
    <h4><b><u>{{movies.name}}</u></b></h4><br>
    <b>{{movies.year}}</b><br>
    {{movies.desc}}<br>
    <a class="btn btn-warning" href="{% url 'movieapp:update' movies.id %}">Update</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movies.id %}">Delete</a>

</div>

 </div>
</div>
{% endblock %}

movieproject/movieproject/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movieproject/movieproject/templates/movie.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in result %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img  class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="250px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
<!--    <p  class="card-text">{{i.desc}}</p>-->
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">View Details</a>
  </div>
</div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

movieproject/movieproject/templates/movieadd.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter the movie name"><br>
  <input type="text" name="year" placeholder="Enter the movie year"><br>
  <input type="text" name="desc" placeholder="Enter the movie description"><br>
  <input type="file" name="img"><br>
  <input type="submit">
</form>
{% endblock %}